export const CONFIG = {
  step: 1 / 120,
  gravity: 9.81,
  drag: 0.022,
  groundFriction: 1.6,
  radius: 2.2,
  launchHeight: 4.5,
  energyMultiplier: 10,
  baseMass: 1,
  baseHealth: 100,
  safeEnergy: 85,
  lethalEnergy: 125,
  impactThreshold: 13,
  impactDamage: 3.4,
  bounce: 0.46,
  restSpeed: 0.65,
  restTime: 0.65,
  mushroomImpulse: 21,
  mushroomForward: 2,
  mushroomMinSpeed: 2,
  hayDamping: 0.48,
  updraftForce: 6.8,
  windHeight: 52,
  wingLift: 0.13,
  wingBreakSpeed: 16,
  wingWear: 0.35,
  materialMeters: 10,
  trackPeriod: 520,
  defaults: { angle: 38, energy: 70 },
  limits: { angle: [10, 75], energy: [15, 150] },
  upgrades: {
    armor: { name: 'Schalenpanzerung', costs: [25, 60, 110], mass: 0.2, health: 25, safeEnergy: 12, lethalEnergy: 9, benefit: 'Mehr Schale. Mehr Belastbarkeit.', drawback: '+20 % Grundgewicht pro Stufe' },
    wings: { name: 'Gleitflügel', costs: [30, 65, 120], mass: 0, benefit: 'Länger gleiten. Weiter träumen.', drawback: 'Harte Kontakte knicken die Flügel' },
    pads: { name: 'Sprungpolster', costs: [25, 60, 110], mass: 0.12, damageReduction: 0.18, bounce: 0.1, benefit: 'Weicher landen. Höher hüpfen.', drawback: '+12 % Grundgewicht pro Stufe' },
  },
  // Repeated exactly; no random physics or obstacles.
  track: [
    { type: 'mushroom', x: 57, width: 11, height: 5 },
    { type: 'hay', x: 116, width: 13, height: 7 },
    { type: 'wind', x: 151, width: 42, height: 52 },
    { type: 'mushroom', x: 229, width: 13, height: 5 },
    { type: 'wind', x: 280, width: 32, height: 48 },
    { type: 'hay', x: 337, width: 16, height: 7 },
    { type: 'mushroom', x: 408, width: 11, height: 5 },
    { type: 'hay', x: 475, width: 12, height: 6 },
  ],
};
export const UPGRADE_KEYS = Object.keys(CONFIG.upgrades);
export const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
