export const CONFIG = {
  step: 1 / 120,
  talentCap: 20,
  xpPerLevel: 100,
  runXp: 60,
  parentRankRequired: 2,
  gravity: 9.81,
  drag: 0.022,
  groundFriction: 14,
  minBounceSpeed: 6,
  bounceDecayAfter: 3,
  bounceDecay: 0.78,
  plantSpacing: 12,
  plantMinImpact: 4,
  radius: 2.2,
  launchHeight: 18,
  muzzleKick: 1.18,
  rearLaserDistance: 90,
  rearLaserStart: -6,
  energyMultiplier: 10,
  baseMass: 1,
  baseHealth: 100,
  safeEnergy: 85,
  impactThreshold: 13,
  impactDamage: 2.6,
  bounce: 0.46,
  restSpeed: 0.65,
  restTime: 0.65,
  mushroomImpulse: 21,
  mushroomForward: 2,
  mushroomMinSpeed: 2,
  hayDamping: 0.48,
  updraftForce: 22,
  updraftRiseSpeed: 18,
  updraftBraking: 0.7,
  updraftDuration: 5,
  thermalSeed: 73129,
  thermalCount: 5,
  thermalGap: [170, 460],
  boostCooldown: 0.8,
  boostForward: 12,
  boostUpward: 21,
  windHeight: 52,
  wingLift: 0.13,
  wingBreakSpeed: 16,
  wingWear: 0.35,
  materialMeters: 30,
  landingBonus: 3,
  pickupRadius: 3.6,
  pickupGroups: 8,
  pickupHeights: [5, 65],
  chargeSeconds: 1.65,
  maxEnergy: 220,
  extremeEnergy: 175,
  launchRisk: { yellowFailure: .035, extremeFailure: .72, exponent: 1.1, armorProtection: .16, tapeProtection: .17, yellowDamage: .12, extremeDamageMin: .2, extremeDamageSpread: .45 },
  windForce: 0.7,
  trafficSpeed: 13,
  trafficStart: 360,
  trafficSafeDistance: 140,
  trafficGrace: 1.5,
  trafficRadius: 3.4,
  trafficBounce: 24,
  trafficBoostRecharge: 1,
  trackPeriod: 520,
  defaults: { angle: 38, energy: 70 },
  limits: { angle: [8, 80], energy: [20, 220] },
  upgrades: {
    armor: { name: 'Schalenpanzerung', ranks: 3, mass: 0.2, health: 25, safeEnergy: 12, benefit: 'Stabilere Starts und eine robustere Schale.', drawback: '+20 % Grundgewicht pro Stufe' },
    wings: { name: 'Gleitflügel', ranks: 3, mass: 0, benefit: 'Länger gleiten. Weiter träumen.', drawback: 'Harte Kontakte knicken die Flügel' },
    pads: { name: 'Sprungpolster', ranks: 3, mass: 0.12, damageReduction: 0.22, bounce: 0.15, benefit: 'Trampolin-Landungen statt lahmem Hüpfen.', drawback: '+12 % Grundgewicht pro Stufe' },
    braces: { name: 'Panzertape', ranks: 3, parent: 'armor', benefit: 'Senkt das Risiko beim Überladen.', drawback: 'Tape wiegt auch etwas', mass: 0.06 },
    airbag: { name: 'Notfall-Airbag', ranks: 3, parent: 'braces', parents: ['braces', 'sail'], benefit: 'Fängt Schaden der ersten harten Landung ab.', drawback: 'Einmal pro Flug; zusätzliches Gewicht', mass: 0.1 },
    sail: { name: 'Sturmsegel', ranks: 3, parent: 'wings', benefit: 'Mehr Schub durch Rücken- und Aufwind.', drawback: 'Auch Gegenwind packt kräftiger zu', mass: 0 },
    streamline: { name: 'Rennschale', ranks: 3, parent: 'sail', parents: ['sail', 'springs'], benefit: 'Weniger Luftwiderstand, mehr Tempo.', drawback: 'Harte Landungen tun mehr weh', mass: 0 },
    springs: { name: 'Sprungverstärker', ranks: 3, parent: 'pads', benefit: 'Alle Sprungbretter katapultieren dich höher.', drawback: 'Schwere Federn an den Füßen', mass: 0.08 },
    rocket: { name: 'Dosenrakete', ranks: 3, parent: 'springs', parents: ['springs', 'satchel'], benefit: 'Automatischer Schub kurz nach dem Start.', drawback: 'Schwer und schwer zu kontrollieren', mass: 0.18 },
    magnet: { name: 'Schrottmagnet', ranks: 3, benefit: 'Sammelt Schrott aus größerer Entfernung.', drawback: 'Mehr Magnet, mehr Gewicht', mass: 0.07 },
    satchel: { name: 'Beuteltasche', ranks: 3, parent: 'magnet', benefit: 'Jedes eingesammelte Teil ist mehr wert.', drawback: 'Die Tasche macht die Knolle schwerer', mass: 0.08 },
    recycler: { name: 'Resteverwerter', ranks: 3, parent: 'satchel', parents: ['satchel', 'braces'], benefit: 'Mehr XP aus Strecke und heiler Landung.', drawback: 'Extra Gewicht; Bonus nur beim Überleben', mass: 0.06 },
  },
  // Fixed obstacle geometry; launch variation and wind live in world.mjs.
  track: [
    { type: 'mushroom', x: 57, width: 11, height: 5 },
    { type: 'hay', x: 116, width: 13, height: 7 },
    { type: 'mushroom', x: 229, width: 13, height: 5 },
    { type: 'hay', x: 337, width: 16, height: 7 },
    { type: 'mushroom', x: 408, width: 11, height: 5 },
    { type: 'hay', x: 475, width: 12, height: 6 },
  ],
};
export const UPGRADE_KEYS = Object.keys(CONFIG.upgrades);
export const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
export const LEVELS = {
  ground: { id: 'ground', number: '01', name: 'Schrottplatz', subtitle: 'Von unten nach ganz oben.', gravity: 18, launchHeight: 18, launchScale: 1.85, windScale: 1, dragScale: 1, boostScale: 1, boosts: 2, next: null, targetDistance: 300, targetHeight: 90 },
  sky: { id: 'sky', number: '02', name: 'Wolkenflieger', subtitle: 'Die Kanone fliegt jetzt mit.', gravity: 6.2, launchHeight: 80, launchScale: 2.35, windScale: .45, dragScale: .45, boostScale: 2.5, boosts: 3, next: 'space', targetDistance: 1200, targetHeight: 700 },
  space: { id: 'space', number: '03', name: 'Sternenknolle', subtitle: 'Nächster Halt: außerhalb des Sonnensystems.', gravity: 2.2, launchHeight: 18, launchScale: 3.7, windScale: 0, dragScale: .04, boostScale: 4, boosts: 4, next: null, targetDistance: 4200, targetHeight: 800 },
};
export const levelConfig = id => LEVELS[id] || LEVELS.ground;
export const SPACE_MARKERS = [
  { x: 350, name: 'Mars', color: '#d28d75', radius: 19 },
  { x: 1000, name: 'Jupiter', color: '#ddbd98', radius: 41 },
  { x: 1850, name: 'Saturn', color: '#d3be98', radius: 32, ring: true },
  { x: 2800, name: 'Neptun', color: '#94a8dd', radius: 24 },
  { x: 4200, name: 'HELIOPAUSE', color: '#d6eed7', radius: 0 },
];
export const BRANCHES = [
  { name: 'UNZERKNOLLBAR', color: '#ffb85b', keys: ['armor', 'braces', 'airbag'] },
  { name: 'LUFTNUMMER', color: '#8edce4', keys: ['wings', 'sail', 'streamline'] },
  { name: 'ESKALATION', color: '#f296d1', keys: ['pads', 'springs', 'rocket'] },
  { name: 'BEUTEZUG', color: '#d4e679', keys: ['magnet', 'satchel', 'recycler'] },
];
export const LEGACY_ACHIEVEMENTS = ['aviator', 'orbital', 'escape'];
export const ACHIEVEMENTS = [
  { id: 'wrongway', icon: 'bolt', name: 'Falscher Ausgang', description: 'Lass dich nach einem Rückwärtsflug vom Sicherheitslaser erwischen.' },
  { id: 'seedling', icon: 'leaf', name: 'Grüner Daumen', description: 'Pflanze insgesamt 10 Kartoffeln.' },
  { id: 'gardener', icon: 'leaf', name: 'Knollengärtner', description: 'Pflanze insgesamt 50 Kartoffeln.' },
  { id: 'farmer', icon: 'leaf', name: 'Kartoffelimperium', description: 'Pflanze insgesamt 200 Kartoffeln.' },
  { id: 'first', icon: 'flag', name: 'Ab durch die Schale', description: 'Beende deinen ersten Flug.' },
  { id: 'naked', icon: 'bolt', name: 'Nackt im Überschall', description: 'Überlebe einen extremen Start ohne Panzerung, Tape und Airbag mindestens 3 Sekunden.' },
  { id: 'collector', icon: 'magnet', name: 'Schrott gehört mir', description: 'Sammle 8 schwebende Teile in einem Flug.' },
  { id: 'distance', icon: 'wings', name: 'Falsche Postleitzahl', description: 'Fliege 500 Meter weit.' },
  { id: 'bounce', icon: 'pads', name: 'Schrott-Pinball', description: 'Erwische 2 Sprungbretter in einem Flug.' },
  { id: 'traffic', icon: 'rocket', name: 'Rechts vor Knolle', description: 'Überlebe eine Begegnung mit Gegenverkehr.' },
  { id: 'landing', icon: 'armor', name: 'Noch ganz brauchbar', description: 'Lande nach 200 Metern mit mindestens halber Schale.' },
  { id: 'tinkerer', icon: 'gear', name: 'Bastelbude', description: 'Verteile alle 20 Talentpunkte.' },
];

export const BOUNCERS = {
  mushroom: { name: 'Sprungpilz', impulse: 1, forward: 2 },
  trampoline: { name: 'Trampolin', impulse: .85, forward: 8 },
  spring: { name: 'Schrottfeder', impulse: 1.2, forward: 1 },
  toaster: { name: 'Kartoffel-Toaster', impulse: 1.05, forward: 4 },
};
